### ISSUE TITLE
猫端开服报错

### ISSUE THREAD

**Issue by Lonelyxiya** [joe-vettek/Dynamic-Trees-for-Sakura#1]
[latest.log](https://github.com/joe-vettek/Dynamic-Trees-for-Sakura/files/7915390/latest.log)
请修复猫端开服报错这个问题

**Comment by joe-vettek** [comment]
这个问题已经定位，但是很抱歉我目前没有时间修复，理想情况需要后天上午才能修复，今晚有时间的话也可能修。

**Comment by joe-vettek** [comment]
已经修了
