### ISSUE TITLE
多人游戏中落叶效果丢失

### ISSUE THREAD

**Issue by Curitis-TK** [joe-vettek/Dynamic-Trees-for-Sakura#2]
## 问题描述
多人游戏中，树叶落叶效果丢失
![mp](https://user-images.githubusercontent.com/45293781/150902040-a7961da0-aded-46db-96d8-a88f3a7318fc.png)

单人模式中效果能正常呈现
![sp](https://user-images.githubusercontent.com/45293781/150902587-63586665-8683-4ef0-aa81-68fc6a35193d.png)

## 环境
- CatServer-c0537be
- DynamicTrees-1.12.2-0.9.26
- MMLib-2.3.0
- **Dynamictrees-sakura-compact-1.12.2-1.4.0.1**

**Comment by joe-vettek** [comment]
修了
