### ISSUE TITLE
偶发服务器崩溃

### ISSUE THREAD

**Issue by Curitis-TK** [joe-vettek/Dynamic-Trees-for-Sakura#3]
## 问题描述
多人游戏中，偶发服务器崩溃。
事发突然，抱歉目前仅能提供错误报告，我会持续尝试看能否复现问题以提供更好的描述

## crash-report
[crash-2022-02-08_21.06.11-server.txt](https://github.com/joe-vettek/Dynamic-Trees-for-Sakura/files/8030384/crash-2022-02-08_21.06.11-server.txt)
[crash-2022-02-08_23.31.11-server.txt](https://github.com/joe-vettek/Dynamic-Trees-for-Sakura/files/8030386/crash-2022-02-08_23.31.11-server.txt)

## 环境
- CatServer-c0537be
- DynamicTrees-1.12.2-0.9.26
- MMLib-2.3.0
- **Dynamictrees-sakura-compact-1.12.2-1.4.0.2**

**Comment by joe-vettek** [comment]
原因大概已经定位了

**Comment by joe-vettek** [comment]
不需要再复现情况

**Comment by joe-vettek** [comment]
目前建议把所有的枫糖龙头卸下来，等今天我发布新版本之后再测试一下。

**Comment by Curitis-TK** [comment]
感谢

**Comment by joe-vettek** [comment]
目前已经完成修复了这个问题，不过发现了一个奇怪的小问题（虽然不会崩服，但是感觉可能看起来不太合适），可能还要一会。

**Comment by joe-vettek** [comment]
可以下载更新了。
