### ISSUE TITLE
1.18.2 添加此模组会导致无法打开暮色传送门

### ISSUE THREAD

**Issue by ofkarosia** [joe-vettek/Dynamic-Trees-for-Sakura#4]
![2024-06-16_16 24 23](https://github.com/joe-vettek/Dynamic-Trees-for-Sakura/assets/147628289/db768590-0b91-49cd-b11a-c48da956a0f2)
![2024-06-16_16 30 53](https://github.com/joe-vettek/Dynamic-Trees-for-Sakura/assets/147628289/caca10f5-acc9-4345-94b0-8b610e7019ea)

最小复现：
```text
dtsakuracompact-1.18.2-1.0.2-beta.jar
DynamicTrees-1.18.2-1.0.4.jar
mmlib-1.4.7-1.18.2.jar
sakura-1.0.7-1.18.2.jar
twilightforest-1.18.2-4.1.1494-universal.jar
```

**Comment by joe-vettek** [comment]
if delete this mod, could you create the transport portal?

如果删除这个模组，你是否可以创建传送门？

**Comment by ofkarosia** [comment]
删除本模组后可以创建传送门

**Comment by joe-vettek** [comment]
by the way, you also need delete Dynamic Trees mod.

在进行测试的时候，你必须同时删除动态树模组。

**Comment by ofkarosia** [comment]
只安装TF，以及安装TF和Sakura均可创建传送门

**Comment by joe-vettek** [comment]
You forgot about Dynamic Trees.

你忘记了动态树。这个模组是动态树的附属，本身没有太多代码。但是动态树有很多代码。

**Comment by joe-vettek** [comment]
I tested it and it's missing. This is very strange.

我确实测试了，很奇怪。

**Comment by joe-vettek** [comment]
Great thanks. It's fixed.

非常感谢，已经被修复。CurseForge已经上传了新的版本。问题与错误的数据包有关。1.18.2的樱还不完成。樱的作者告诉我说可能会未来直接更新1.20.1（现在看来可能不行了，1.21出来了）。
